name: Deploy Production Frontend

on:
  push:
    branches: ['production']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project directly to target directory
        run: npm run build -- --outDir ${{ secrets.DISTRIBUTION_PATH }}
        
      - name: Reload nginx
        run: |
          sudo systemctl reload nginx
